version: '3.9'
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    env_file:
      - ./.env.local
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - 'mongo:/data/db'

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    env_file:
      - ./.env.local
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - '${DEV_MNEMONIC}'
      - --networkId
      - '1337'
      - --hostname
      - '0.0.0.0'
      - --debug

  truffle-deploy:
    build:
      context: ./
      dockerfile: ./evm/Dockerfile.dev
    env_file:
      - ./.env.local
    volumes:
      - ./:/app
      - /app/node_modules
    links:
      - ganache
    command: bash -c "while ! curl -s ganache:8545 > /dev/null; do echo waiting for xxx; sleep 3; done; npm run deploy:docker"

  web-user:
    depends_on:
      - ganache
      - mongo
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./.env.local
    command: npm run dev
    volumes:
      - ./:/app:rw
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

volumes:
  mongo: